/*
 * Stoatworks Labs - About window data for Receipt.
 *
 * PROVISIONAL HAND COPY, adapted from toner's on 2026-09-25. The fleet's
 * version is GENERATED by stoatworks-backend/scripts/sync-about.py from the
 * website's projects.json; this project is not registered there yet, so the
 * release step registers it and re-runs the sync, which overwrites this file.
 *
 * `guide` is empty because no user guide exists yet: StoatworksAboutLinks.h
 * leaves a button out rather than showing one that opens a 404, so the host
 * shows three About buttons, not four.
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "Receipt";
    inline constexpr auto slug = "receipt";
    inline constexpr auto hook = "A thermal receipt printer, for Resolume";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "";
    inline constexpr auto page = "https://stoatworks-labs.com/software/receipt/";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/receipt";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
